packages: []
catalogs:
  cli:
    bumpp: ^10.3.1
    pncat: ^0.7.6
    taze: ^19.9.0
  frontend:
    react: ^19.2.0
  lint:
    '@antfu/eslint-config': ^6.2.0
    '@eslint-react/eslint-plugin': ^2.3.5
    eslint: ^9.39.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  network:
    ofetch: ^1.5.1
    ws: ^8.18.3
  raycast:
    '@raycast/api': ^1.103.6
    '@raycast/utils': ^2.2.2
  script:
    tsx: ^4.20.6
  test:
    vitest: ^4.0.10
  tsc:
    typescript: ^5.9.3
  types:
    '@types/node': ^24.10.1
    '@types/react': ^19.2.6
    '@types/ws': ^8.18.1
  utils:
    run-applescript: ^7.1.0
    ufo: ^1.6.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
